### ISSUE TITLE
URL Display Behavior

### ISSUE THREAD

**Issue by sqkkyzx** [rajnandan1/kener#100]
In the description, some URLs are displayed while others are not. I would like to know what determines this. Is it based on using the domain name or the IP address? Can I hide the domain name?

**Comment by rajnandan1** [comment]
This is how it works
- Add a description to the monitor if it is website using api.url and method = GET and headers == undefine
- call the api to see if received content-type is text/html
- if yes, append to description

**Comment by sqkkyzx** [comment]
Based on the working principle you provided, I have hidden the URL with the following settings:
```yaml
headers:
  show-url: false
```
It might seem a bit amusing. I will not close this issue for now, in case it helps others. However, it would be better to update it in the documentation.

**Comment by rajnandan1** [comment]
This has been fixed and doc has been updated
https://kener.ing/docs/monitor-examples/#simple-get-monitor-without-hyperlink

```yaml
- name: Google Search
  tag: "google-search"
  api:
      method: GET
      url: https://www.google.com/webhp
      hideURLForGet: true # this is how you would want to do it
```
