### ISSUE TITLE
Adjust the 90-day cycle

### ISSUE THREAD

**Issue by chen5293** [rajnandan1/kener#105]
Is there any way to adjust the 90-day cycle?
And reduce the frequency of monitoring, for example once every 10 minutes
I tried using cron but it didn't work

**Comment by rajnandan1** [comment]
To reduce the frequency of monitoring your will have to do it like this
This will run every two minutes
```yaml
- name: Earth
  description: Our blue planet
  tag: "earth"
  defaultStatus: "UP"
  image: "/earth.png"
  cron: "*/2 * * * *"
```
