### ISSUE TITLE
Custom DNS resolver and listening to TCP ports

### ISSUE THREAD

**Issue by hapugov** [rajnandan1/kener#111]
**Is your feature request related to a problem? Please describe.**
None [...]

**Describe the solution you'd like**
Hello, there is no problem, but it would be great if the kenner was smart enough to listen to TCP ports and have on board checking the response of the web server using the specified DNS server, as is done by Gatus:

**Describe alternatives you've considered**

```
An example with DNS
    - name: hidden
        group: hidden
        url: 'https://hidden'
        client:
          dns-resolver: 'tcp://hidden:53'
          timeout: 10s
          insecure: true
          ignore-redirect: false
        ui: 
          hide-hostname: true
        interval: 5m
        conditions:
          - '[STATUS] == 200' 


    Example with TCP port listening  
        - name: hidden
        group: hidden
        url: 'tcp://hidden:3033'
        client:
         timeout: 10s
         insecure: true
        ui: 
         hide-hostname: true
        interval: 5m
        conditions:
        - '[CONNECTED] == true'

```

**Additional context**
