### ISSUE TITLE
docker recent incidents not visible

### ISSUE THREAD

**Issue by Aviortheking** [rajnandan1/kener#185]
**Describe the bug**
When accessing the recent incidents tab when using the docker image it seems it does not reconize the `GH_TOKEN`

**To Reproduce**
1. launch the app using docker-compose
2. create an incident
3. resolve it
4. click on Recent incidents
5. nothing appear and a message in the server logs `Github owner or repo or GH_TOKEN is undefined. Read the docs to configure github: https://kener.ing/docs/gh-setup/` while it works with current incidents

**Expected behavior**
recent incidents should appear

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 133.0.3

**Additional context**
the docker-compose.yml file I use
```yml
version: "3.3"
services:
  kener:
    volumes:
      - ./database:/app/database
      - ./config:/app/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.status-tcgdex-net.rule=Host(`status.tcgdex.net`)
      - traefik.http.services.status-tcgdex-net.loadbalancer.server.port=3000
      - traefik.http.routers.status-tcgdex-net.tls.certresolver=letsencrypt
    environment:
      - GH_TOKEN=**************************************
    image: rajnandan1/kener
    networks:
      - infra
networks:
  infra:
    external: true
x-dockge:
  urls:
    - https://status.tcgdex.net
```
