### ISSUE TITLE
couldn't run migrations on first start using sqlite

### ISSUE THREAD

**Issue by moda20** [rajnandan1/kener#188]
**Describe the bug**
can't stop the docker container due to migrations failing on the SQLite level 

**To Reproduce**
1. use the official compose file : https://raw.githubusercontent.com/rajnandan1/kener/main/docker-compose.yml (with slight modification)
2. run docker compose 
3. check logs to see the error 

**Expected behavior**
normal migrations running, and correct first start

**Desktop (please complete the following information):**
 - OS: linux 24.04 / docker

**Additional context**

docker compose config : 

```yaml
version: '3.8'
services:
  kener:
    image: rajnandan1/kener:latest
    container_name: kener
    #env_file: .env #uncomment this, if you are using .env file
    environment:
      - TZ=Etc/UTC
      - NODE_ENV=production
      #- GH_TOKEN=
      #- PORT=3000
      #- KENER_BASE_PATH=
      #- RESEND_API_KEY=
      #- ORIGIN=
      #- KENER_SECRET_KEY=

      # If running on a LINUX HOST and not podman rootless these MUST BE SET
      # run "id $user" from command line and replace numbers below with output from command
      #- PUID=0 # gid
      #- PGID=0 # uid

      ### Most likely DO NOT need to change anything below this ###

      #- PORT=3000 Port app listens on IN CONTAINER
    ports:
      - '8094:3000/tcp'
    volumes:
      - './db:/app/database:rw' # <== i only modified the volume
```

error logs : 

```
Running migrations...

/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5
	return this[cppdb].prepare(sql, this, false);
	                   ^
SqliteError: select * from `monitors` where `status` = 'ACTIVE' order by `id` desc - no such table: monitors
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Client_BetterSQLite3._query (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:35:34)
    at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/app/node_modules/knex/lib/client.js:154:12)
    at Runner.query (/app/node_modules/knex/lib/execution/runner.js:141:36)
    at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:318:20)
    at async Runner.run (/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async DbImpl.getMonitors (file:///app/src/lib/server/db/dbimpl.js:250:10)
    at async GetMonitorsParsed (file:///app/src/lib/server/controllers/controller.js:193:17) {
  code: 'SQLITE_ERROR'
}

Node.js v23.6.0
 
```
