### ISSUE TITLE
grid layout

### ISSUE THREAD

**Issue by Famku** [rajnandan1/kener#275]
is it possible to set a grid layout for the monitors?

maybe with custom css?

**Comment by rajnandan1** [comment]
Yes. You can write custom css to have your own grid.

**Comment by rajnandan1** [comment]
Will try but can you help me understand what kind of grid you are looking for.

**Comment by rajnandan1** [comment]
here is the css you can use

```css
@media (min-width: 1330px) {
  .section-monitors,
  .section-categories,
  .section-hero,
  .section-back,
  .section-events,
  .section-legend,
  .section-categories,
  .section-browser-events {
    width: 1330px !important;
    max-width: 1330px !important;
  }

  .section-monitors .monitor-root {
    background-color: transparent;
    border: none !important;
    box-shadow: none;
  }

  .section-monitors .monitor-root .monitors-card {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 0.5rem; /* Equivalent to Tailwind's gap-2 */
  }

  .section-monitors .monitor-root .monitors-card .monitor {
    grid-column: span 1;
    border-radius: 0.375rem;
    background-color: hsl(var(--card) / var(--tw-bg-opacity, 1));
    border-width: 1px;
  }
  .section-monitors .monitor-root .monitors-card .monitor:last-child {
    border-bottom: inherit;
    border-bottom-width: 1px !important;
  }
}
```
