### ISSUE TITLE
/app/package.json ERROR on fresh install

### ISSUE THREAD

**Issue by 0PandaDEV** [rajnandan1/kener#346]
**Describe the bug**
I get this in the docker compose logs upon a complete fresh install.
```log
kener  | Running migrations...
kener  | Migrations completed successfully!
kener  | Running seed...
kener  | Seed completed successfully!
kener  | Error reading version: Error: ENOENT: no such file or directory, open '/app/package.json'
kener  |     at Object.readFileSync (node:fs:443:20)
kener  |     at getVersion (file:///app/src/lib/server/startup.js:22:39)
kener  |     at Startup (file:///app/src/lib/server/startup.js:88:19)
kener  |     at Server.<anonymous> (file:///app/main.js:97:2) {
kener  |   errno: -2,
kener  |   code: 'ENOENT',
kener  |   syscall: 'open',
kener  |   path: '/app/package.json'
kener  | }
kener  | Kener is running on port 3000!
kener  | ADDING NEW JOB WITH NAME Tag: earth Hash:7d46a5854dda1d6bd56537d13481489323081bc65a8ce1abc0242bec1de1f25a
kener  |   _  __                                        _                              
kener  |  | |/ /___ _ __   ___ _ __  __   ___   _ _ __ | | ___ __   _____      ___ __  
kener  |  | ' // _ \ '_ \ / _ \ '__| \ \ / / | | | '_ \| |/ / '_ \ / _ \ \ /\ / / '_ \ 
kener  |  | . \  __/ | | |  __/ |     \ V /| |_| | | | |   <| | | | (_) \ V  V /| | | |
kener  |  |_|\_\___|_| |_|\___|_|      \_/  \__,_|_| |_|_|\_\_| |_|\___/ \_/\_/ |_| |_|
kener  |                                                                               
kener  | Kener version unknown is running!
```

**To Reproduce**
1. Fresh install

**Version**
3.2.4

**Environment**
docker compose

**Database**
sqlite

**Expected behavior**
Normal run

```yml
services:
  kener:
    image: rajnandan1/kener:latest
    container_name: kener
    environment:
      TZ: Etc/UTC
      KENER_SECRET_KEY: cb0***
      RESEND_API_KEY: re_es**
      RESEND_SENDER_EMAIL: kener@pandadev.net
      ORIGIN: https://kener.pandadev.net
    ports:
      - '8003:3000/tcp'
    volumes:
      - data:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  data:
    name: kener_db
```
