### ISSUE TITLE
Cross-site POST form submissions are forbidden

### ISSUE THREAD

**Issue by 0PandaDEV** [rajnandan1/kener#365]
**Describe the bug**
When I attempt to login or register, I get this error message 

**To Reproduce**
1. Setup instance
2. Attempt to login or register

**Version**
3.2.10

**Environment**
docker compose

**Database**
sqlite

**Screenshots**
`https://****/manage/setup/submit`
![Image](https://github.com/user-attachments/assets/0a38bba5-550c-445b-bde6-24eacc5c8750)

**Additional context**
```yml
services:
  kener:
    image: rajnandan1/kener:latest
    container_name: kener
    environment:
      TZ: Europe/Zurich
      KENER_SECRET_KEY: ****
      RESEND_API_KEY: ****
      RESEND_SENDER_EMAIL: ****

      PORT: 3000
      ORIGIN: http://localhost:3000
      NODE_ENV: production
    ports:
      - '8004:3000/tcp'
    volumes:
      - db:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  db:
```
