### ISSUE TITLE
health check api endpoint

### ISSUE THREAD

**Issue by RomRider** [rajnandan1/kener#391]
**Is your feature request related to a problem? Please describe.**
For livenessprobe (k8s) or healthcheck (docker), it would be great to have an unauthenticated API endpoint to check the health of the kener itself.

**Describe the solution you'd like**
Somethine like `/api/health` would return `{ "status": "OK" }` (or `KO`) and http status 200 (or 400 if there's something wrong).

**Describe alternatives you've considered**
Using `/` to check health is taking a long time if you have a lot of monitors and requires to increase the response timeout to 5s to make sure the pod is not killed. 

**Additional context**
```yaml
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
```
