### ISSUE TITLE
Ability to disable the "Subscribe to Updates" button

### ISSUE THREAD

**Issue by russjr08** [rajnandan1/kener#418]
**Is your feature request related to a problem? Please describe.**
I do not have plans to utilize the email notifications feature, so it would be nice to be able to remove the `Subscribe to Updates` option from the status home page.

**Describe the solution you'd like**
An option could be implemented in the `Home` or `Site` settings area to disable the option from appearing on the home page.

**Describe alternatives you've considered**
Alternatively, this could be controllable with an environmental variable - though a UI setting would probably be better for this.

**Additional context**
Apologies if I've missed an existing setting for this somewhere!

**Comment by ToxykAuBleu** [comment]
In a way, you can do it by using custom CSS. Go to your panel, and go to theme, go all the way down and you should have custom CSS.  Choose what you want to disable between those selectors:

- All buttons:

```css
.section-actions:not(.status-color-banner) {
    display: none
}
```

- Specifically Subscribe to Updates:

```css
.section-actions > div > button {
    display: none
}
```

- Specifically Next maintenances:

```css
.section-actions > div > a {
    display: none
}
```

(You can always custom these buttons by applying correct css rules, as you want 🙂 )
