### ISSUE TITLE
Support navigating to the website

### ISSUE THREAD

**Issue by orhun** [rajnandan1/kener#45]
**Is your feature request related to a problem? Please describe.**

Currently I use the `description` field to paste the website address that is being checked:

```yaml
- name: Website
  description: https://orhun.dev
  tag: website
  image: "https://orhun.dev/img/crow.png"
  api:
    method: GET
    url: https://orhun.dev
```

![image](https://github.com/rajnandan1/kener/assets/24392180/3e193af2-c25b-4fae-b404-a385c472d84f)

**Describe the solution you'd like**

It would be nice to have a button to open the website in a new tab.

**Describe alternatives you've considered**
None.

**Additional context**
Maybe this is possible somehow but I couldn't find it.

My instance is here: https://status.orhun.dev

**Comment by rajnandan1** [comment]
This is already supported. HTML is supported in description

### Example

```yaml
- name: Website
  description: <a class="font-medium underline underline-offset-4" href="https://www.frogment.com" target="_blank">https://orhun.dev</a>
  tag: website
  image: "https://orhun.dev/img/crow.png"
  api:
    method: GET
    url: https://orhun.dev
```
